// <auto-generated />
namespace Megastore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialProduct_CategoryMenu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialProduct_CategoryMenu));
        
        string IMigrationMetadata.Id
        {
            get { return "201902200028277_Initial-Product_Category-Menu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
